8-Link entity-owner with user
anaCode26/Java-Spring-Boot-Project pull request #11
Opened 2024-12-24 11:28 UTC by anaCode26

Name and address added to the owner.

2024-12-31 12:39 UTC, rdiazutn reviewed
Leaving some comments

2024-12-31 12:39 UTC, rdiazutn commented on restservice/src/main/java/com/example/restservice/pet/model/Owner.java
> +    @SequenceGenerator(name = "owner_sequence", sequenceName = "owner_sequence", allocationSize = 1)
Are you sure this is necessary?

2024-12-31 12:39 UTC, rdiazutn commented on restservice/src/main/java/com/example/restservice/pet/model/Owner.java
> +@Data
Is this necessary?
According to docs its the same as @getter @setter, etc.

2024-12-31 12:39 UTC, rdiazutn commented on restservice/src/main/java/com/example/restservice/security/model/User.java
> +@Data
Same

2024-12-31 12:39 UTC, rdiazutn commented on restservice/src/main/java/com/example/restservice/security/model/User.java
> +@AllArgsConstructor
Create a constructor instead

2024-12-31 12:41 UTC, rdiazutn commented
You are also missing:
- a good PR description
- linking the PR to an issue

2025-01-01 10:50 UTC, anaCode26 commented on restservice/src/main/java/com/example/restservice/security/repository/RoleRepository.java
> +import java.util.Optional;
deleted!

2025-01-01 10:54 UTC, anaCode26 commented on restservice/src/main/java/com/example/restservice/security/model/User.java
> +@Data
got it!

2025-01-01 10:55 UTC, anaCode26 commented on restservice/src/main/java/com/example/restservice/security/model/User.java
> +    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "user_sequence")
i don't know. Anyway, I delete it!

2025-01-01 11:15 UTC, anaCode26 commented on restservice/src/main/java/com/example/restservice/security/model/User.java
> +@AllArgsConstructor
But I can use this annotation and have less code.

2025-01-01 11:16 UTC, anaCode26 commented on restservice/src/main/java/com/example/restservice/pet/model/Owner.java
> +@Data
Deleted!

2025-01-01 11:17 UTC, anaCode26 commented on restservice/src/main/java/com/example/restservice/pet/model/Owner.java
> +    @SequenceGenerator(name = "owner_sequence", sequenceName = "owner_sequence", allocationSize = 1)
Yes, is necessary. This automatically assign a unique number whenever I add a new user. Without @SequenceGenerator annotation can cause a duplicate key error.

2025-01-01 11:25 UTC, anaCode26 commented on restservice/src/main/java/com/example/restservice/pet/model/Owner.java
> +    @SequenceGenerator(name = "owner_sequence", sequenceName = "owner_sequence", allocationSize = 1)
Yes, it is. It is related with the comment in the User file.

2025-01-01 11:57 UTC, rdiazutn requested changes

2025-01-01 11:57 UTC, rdiazutn commented on restservice/src/main/java/com/example/restservice/security/repository/RoleRepository.java
> +import java.util.Optional;
It is still here...

2025-01-01 11:57 UTC, rdiazutn commented on restservice/src/main/java/com/example/restservice/pet/model/Owner.java
> +@Data
It is still here...

2025-01-01 11:57 UTC, rdiazutn commented on restservice/src/main/java/com/example/restservice/security/dto/RegistrationDTO.java
> +public class RegistrationDTO {
You can use a record instead

2025-01-01 11:57 UTC, rdiazutn commented on restservice/src/main/java/com/example/restservice/security/model/User.java
> +@AllArgsConstructor
Consistency...
Do you really need this annotaiton?

2025-01-01 11:57 UTC, rdiazutn commented on restservice/src/main/java/com/example/restservice/security/model/User.java
> +    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "user_sequence")
With @GeneratedValue(strategy=GenerationType.IDENTITY) it should be enough, you don't need to specify the sequence...

2025-01-01 17:00 UTC, anaCode26 commented on restservice/src/main/java/com/example/restservice/security/model/User.java
> +    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "user_sequence")
done!

2025-01-01 17:03 UTC, anaCode26 commented on restservice/src/main/java/com/example/restservice/pet/model/Owner.java
> +    @SequenceGenerator(name = "owner_sequence", sequenceName = "owner_sequence", allocationSize = 1)
Sequence was replaced by identity.

2025-01-01 17:22 UTC, anaCode26 commented on restservice/src/main/java/com/example/restservice/security/dto/RegistrationDTO.java
> +public class RegistrationDTO {
Done!

2025-01-01 18:05 UTC, rdiazutn approved these changes

2025-01-01 18:05 UTC, merged