Fixing the warnings
anaCode26/Java-Spring-Boot-Project pull request #12
Opened 2024-12-24 11:52 UTC by anaCode26

2024-12-31 12:47 UTC, rdiazutn requested changes

2024-12-31 12:47 UTC, rdiazutn commented on restservice/src/main/java/com/example/restservice/pet/controller/OwnerController.java
> +    //public Owner getCostFoodOwner(@PathVariable("id") int id) { return ownerService.getAmountFoodPerOwner(id);}
Commented code

2024-12-31 12:47 UTC, rdiazutn commented on restservice/src/main/java/com/example/restservice/security/model/User.java
> +    @ManyToMany(fetch = FetchType.EAGER, cascade = {CascadeType.DETACH, CascadeType.MERGE, CascadeType.PERSIST, CascadeType.REFRESH})
Do you know the implicances of this?

2025-01-05 11:35 UTC, anaCode26 commented on restservice/src/main/java/com/example/restservice/pet/controller/OwnerController.java
> +    //public Owner getCostFoodOwner(@PathVariable("id") int id) { return ownerService.getAmountFoodPerOwner(id);}
removed.

2025-01-05 11:37 UTC, anaCode26 commented on restservice/src/main/java/com/example/restservice/security/model/User.java
> +    @ManyToMany(fetch = FetchType.EAGER, cascade = {CascadeType.DETACH, CascadeType.MERGE, CascadeType.PERSIST, CascadeType.REFRESH})
Not really. I fixed.

2025-01-06 18:56 UTC, rdiazutn approved these changes

2025-01-06 18:56 UTC, merged